### ISSUE TITLE
We can't erase little dots

### ISSUE THREAD

**Issue by hackerwins** [yorkie-team/yorkie-codepair#106]
**What happened**:

We can't erase little dots.

![chrome-capture](https://user-images.githubusercontent.com/2059311/116511470-72bd4480-a901-11eb-8085-2bce40cbc24f.gif)

**What you expected to happen**:

It is erased normally.

**How to reproduce it (as minimally and precisely as possible)**:

- Draw a small dot.
- Select the eraser and try to erase it.

**Anything else we need to know?**:

**Environment**:
- Operating system: macOS Big Sur, Version 11.1
- Browser and version: Chrome Version 88.0.4324.96

**Comment by ppeeou** [comment]
It seems that we can solve this with bellow method
1. crosswise elimination method(now)
2. range check from the point
