### ISSUE TITLE
Users can update code editor settings such as theme, keymap(emacs, vim, sublime, ...), and tap size.

### ISSUE THREAD

**Issue by ppeeou** [yorkie-team/yorkie-codepair#11]
- Save it on Local storage

**Comment by ppeeou** [comment]
@hackerwins 
As we discussed earlier, we are going to share the work.

- Localstorage management interface
- CodePair editor setting

Could you proceed with the part  "Localstorage management interface"

**Comment by hackerwins** [comment]
@ppeeou 
Thanks for the comments. However, I would like to do feature-related work. Can I implement the editor settings?

**Comment by ppeeou** [comment]
@hackerwins yes sure 👍🏼 

I think we can divide the editing part down

- action (tab size, keymap, theme, language) (https://github.com/yorkie-team/yorkie-codepair/pull/18/commits/182b2d296bc85039dbfe2db149f96a2e6c67049f#diff-033253188f3f501e8e39a378a39ebae5cb5aa4e75c94a5a23abbcbb26858b7d2)
- reducer  (https://github.com/yorkie-team/yorkie-codepair/pull/18/commits/182b2d296bc85039dbfe2db149f96a2e6c67049f#diff-fe53e443cf7e991de1b5ed7a181fdae0c4607c24dff40e3e3e00558fc9d0f606)
- component(modal editor, select box)

Currently, I am trying to provide it like `Leetcode`. how about you?


![image](https://user-images.githubusercontent.com/10924072/104188300-5ed9f980-545c-11eb-9178-ac9c6188b72a.png)

**Comment by ppeeou** [comment]
@hackerwins 
Not all features have been added yet, could I open it again?
