### ISSUE TITLE
Suggest printWidth size

### ISSUE THREAD

**Issue by ppeeou** [yorkie-team/yorkie-codepair#12]
How about the printWidth size of 120?

.prettierrc.js

````
module.exports = {
  bracketSpacing: true,
  singleQuote: true,
  trailingComma: 'all',
  printWidth: 120,
  tabWidth: 2,
};

```

**Comment by hackerwins** [comment]
I think it is okay to increase `printWidth`.

**Comment by dc7303** [comment]
I think it's okay to try changing the `printWidth` to 120. If we experience any discomfort while using it, it seems that we can make additional adjustments at that time.

**Comment by dc7303** [comment]
@ppeeou 
Any further discussion on this issue? If not, I think you can close it.
