### ISSUE TITLE
Best practice on serverside

### ISSUE THREAD

**Issue by ppeeou** [yorkie-team/yorkie-codepair#13]
I used the following structure.
https://github.com/madhums/node-express-mongoose-demo

other structure
https://github.com/w3tecch/express-typescript-boilerplate
https://github.com/afteracademy/nodejs-backend-architecture-typescript
https://github.com/maximegris/typescript-express-sequelize

guide
https://github.com/mattdesl/module-best-practices

https://github.com/goldbergyoni/javascript-testing-best-practices

**Comment by hackerwins** [comment]
Thanks for the research on the backend. If we need to implement a backend, let's refer to what you've been researching.
