### ISSUE TITLE
Create a new document when clicking the logo on GNB

### ISSUE THREAD

**Issue by hackerwins** [yorkie-team/yorkie-codepair#133]
**Description**:

Create a new document when clicking the logo(`CodePair`) on GNB.

<img width="360" alt="Screen Shot 2021-08-19 at 8 15 20 PM" src="https://user-images.githubusercontent.com/2059311/130059566-348a013e-43d8-47b7-beb0-4247b637efc5.png">

**Why**:

- Users can easily create new documents.

**Comment by starkensin** [comment]
I will try this.
