### ISSUE TITLE
Bump up envoy version to v1.19.0

### ISSUE THREAD

**Issue by hackerwins** [yorkie-team/yorkie-codepair#134]
**Description**:

@blurfx recently updated the Yorkie JS SDK's Envoy settings. Let update Envoy in the same way in CodePair.

https://github.com/yorkie-team/yorkie-js-sdk/issues/227
https://github.com/yorkie-team/yorkie-js-sdk/pull/234

**Why**:

- Keep our code up to date.

**Comment by blurfx** [comment]
i'll do it! (again 😄 )
