### ISSUE TITLE
need to make development environment same.

### ISSUE THREAD

**Issue by starkensin** [yorkie-team/yorkie-codepair#137]
**Eenvironment(local)**:
npm: 6.14.14
node: 14.17.5

**Description**:
When I install dependencies using "npm install" command, the "package-lock.json" file is updated unlike the existing one.

![image](https://user-images.githubusercontent.com/30948699/131224909-b3b86197-f0d6-4b41-a13f-e1f41499b4a8.png)

**Why**:
As we can check the lockFileVersion is different on the above image, I guess this problem is from the development environment is different on person.

**Related issue**:
issue #136

**Comment by ppeeou** [comment]
I think it would be better for users to adapt to the repo environment.

to solve this problem,
How about providing the development environment in the README or creating a Docker file??

**Comment by starkensin** [comment]
I cast a vote for Dockerfile!

**Comment by blurfx** [comment]
If no one is working on it, I'd love to write a Dockerfile.

Also, it would be good to add `.tool-versions` for `asdf` users.

**Comment by ppeeou** [comment]
> If no one is working on it, I'd love to write a Dockerfile.

we'd appreciate it if you did
