### ISSUE TITLE
Choosing a TypeScript style guide

### ISSUE THREAD

**Issue by dc7303** [yorkie-team/yorkie-codepair#14]
We haven't yet chosen the TypeScript style guide, so the discussion of style in PR is growing unnecessarily.
Like this: https://github.com/yorkie-team/yorkie-codepair/pull/10#discussion_r528686623

We have to decide on a style guide.

**Comment by daclouds** [comment]
It seems that Airbnb JavaScript Style Guide is referenced a lot these days. (but some say it is too strict 😉)

- https://github.com/airbnb/javascript
- https://github.com/typescript-eslint/typescript-eslint
- https://www.npmjs.com/package/eslint-config-airbnb

**Comment by ppeeou** [comment]
How about starting https://github.com/airbnb/javascript ??

**Comment by dc7303** [comment]
I agree because I prefer 'Airbnb style'.
For the features provided only in some TypeScript, I suggest the TS style guide of `Typescript deep dive`.

https://basarat.gitbook.io/typescript/styleguide#interface
https://basarat.gitbook.io/typescript/styleguide#type
https://basarat.gitbook.io/typescript/styleguide#type
https://basarat.gitbook.io/typescript/styleguide#enum
https://basarat.gitbook.io/typescript/styleguide#array
https://basarat.gitbook.io/typescript/styleguide#type-vs-interface

**Comment by hackerwins** [comment]
The opinions of the members seem to be gathered.
It would be nice to add [TS style guide](https://basarat.gitbook.io/typescript/styleguide) to the [Airbnb style](https://github.com/airbnb/javascript) guide to introduce a linter and check it in CI.

**Comment by ppeeou** [comment]
I have a problem while this job work. 
There was an [import cycle](
https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-cycle.md) between actions and reducers.

https://github.com/yorkie-team/yorkie-codepair/blob/master/src/reducers/docReducer.ts#L4
https://github.com/yorkie-team/yorkie-codepair/blob/master/src/actions/docActions.ts#L5

I moved it to actions, but please check🙇‍♀️
https://github.com/ppeeou/yorkie-codepair/commit/8b3f617fa9eb8c4052a72070fd5579756df365e0

Except for this, there are no major changes.
First, only the basics were applied.

**Comment by hackerwins** [comment]
@ppeeou Thanks for the tip. If you create PR, it would be nice to look at the `import cycle` problem.
