### ISSUE TITLE
Client sync call location inquiry to know peers early

### ISSUE THREAD

**Issue by ppeeou** [yorkie-team/yorkie-codepair#36]
@hackerwins 
When currently connected, sync is called before subscribe, so the initial peers are not known.

To Get To Know Early Peers
we need to do `client.subscribe` execution before `client.sync`

ref  [client.sync](https://github.com/yorkie-team/yorkie-codepair/blob/main/src/features/docSlices.ts#L52-L72)
ref  [client.subscribe](https://github.com/yorkie-team/yorkie-codepair/blob/main/src/components/Editor/index.tsx#L91)

So I think there are two ways

1. Add a function before sync in attach Doc
2. separate `sync` from attachDoc

I think (2) is better
I think sync is different from attach..

what do you think?

If we run it(1) in attachDoc, it will look like this
 
```
export const attachDoc = createAsyncThunk<AttachDocResult, AttachDocProps, { rejectValue: string }>(
  'doc/attach',
  async ({ docKey, subscribeClient }: AttachDocProps, thunkApi) => {
    try {
      const client = yorkie.createClient(`${process.env.REACT_APP_YORKIE_RPC_ADDR}`);
      const document = yorkie.createDocument('codepairs', docKey);

      await client.activate();
      await client.attach(document);

      document.update((root: any) => {
        if (!root.content) {
          root.createText('content');
        }
      });

      let unSubscribeClient;
      if (subscribeClient) {
        unSubscribeClient = subscribeClient(client);
      }

      await client.sync();
      return { document, client, unSubscribeClient };
    } catch (err) {
      return thunkApi.rejectWithValue(err);
    }
  },
);
```

**Comment by hackerwins** [comment]
I think it's a good idea. However, I think we should be careful that there is no side effect due to the change in motion. Could you post a PR in relation to it?

**Comment by ppeeou** [comment]
@hackerwins 
It was related to this commit
https://github.com/yorkie-team/yorkie-codepair/pull/37/commits/d5f43952619f4bd28cc86a5ca8d10bc137d16427
