### ISSUE TITLE
Intermittent script error: `YORKIE F: the node of the given id should be found`

### ISSUE THREAD

**Issue by hackerwins** [yorkie-team/yorkie-codepair#39]
**What happened**:

I am getting script errors intermittently: `Error: YORKIE F: the node of the given id should be found`
<img width="1016" alt="Screen Shot 2021-02-01 at 15 11 12" src="https://user-images.githubusercontent.com/2059311/106421356-e802b000-649f-11eb-8dbb-0261aec59227.png">

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Operating system: macOS Big Sur, Version 11.1
- Browser and version: Chrome Version 88.0.4324.96

**Comment by ppeeou** [comment]
Does it happen even after syncing the version??🤔

**Comment by hackerwins** [comment]
The pattern was unknown, but it was easily reproduced before, but now it is difficult to reproduce. I will close this issue and open it when it occurs again.
