### ISSUE TITLE
Intermittent script error: `YORKIE F: out of bound of text index: pos: 1 > node.length: 0`

### ISSUE THREAD

**Issue by hackerwins** [yorkie-team/yorkie-codepair#44]
**What happened**:
I am getting script errors intermittently: `YORKIE F: out of bound of text index: pos: 1 > node.length: 0`
<img width="1274" alt="Screen Shot 2021-02-11 at 1 52 49" src="https://user-images.githubusercontent.com/2059311/107542781-e22d6d00-6c0b-11eb-8c1e-12f90ffc3491.png">

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

I couldn't find a pattern to reproduce the bug.

**Anything else we need to know?**:

Yorkie's Documents seem to be synchronizing properly between peers. The problem is caused by a content mismatch between CodeMirror and Document.

```
Client1:                      Client2: 
[CodeMirror <-> Document] <-> [Document <-> CodeMirror]
```

**Environment**:
Operating system: macOS Big Sur, Version 11.1
Browser and version: Chrome Version 88.0.4324.96

**Comment by ppeeou** [comment]
![image](https://user-images.githubusercontent.com/10924072/109455589-55533200-7a9a-11eb-90c8-83b7c63c073c.png)

**Comment by hackerwins** [comment]
@ppeeou Did you find a way to reproduce it?

**Comment by ppeeou** [comment]
@hackerwins Not yet😭 It was discovered during development.
I tried again in the same way, so I couldn't reproduce it

**Comment by hackerwins** [comment]
@ppeeou Looking at the log you uploaded, it seems that `updateSelection` is executed before the `edit` operation. I suspect a situation in which the order of operations is reversed.

**Comment by hackerwins** [comment]
A situation has been discovered where SplayTree fails to contain all nodes of RGATreeSplit in certain situations.
I suspect there is a bug in SplayTree's logic.

```
# Splay Tree
this.getAnnotatedString()
"[1,1]w[6,0]
[3,1]o[1,1]r[2,1]l[4,1]d[0,0]
[0,0]`"

# RGATreeSplit
this.getAnnotatedString()
"[0:00:0:0 ]{26:e1:1:0 
}[8:06:1:0 H][9:06:1:0 e][10:06:1:0 l][11:06:1:0 l][12:06:1:0 o]{39:e1:1:0 
}[41:e1:1:0  ]{24:e1:1:0  }[14:06:1:0 w]{74:e1:1:0 
}[15:06:1:0 o][16:06:1:0 r][17:06:1:0 l][18:06:1:0 d]{28:e1:1:0 
}{29:e1:1:0 `}"
```

**Comment by hackerwins** [comment]
It seems to have been resolved after merging https://github.com/yorkie-team/yorkie-js-sdk/pull/153. If the problem occurs again, we need to reopen this.

**Comment by ppeeou** [comment]
@hackerwins It seems that this problem has not been completely resolved yet..!
Or it could be another problem, so I will try to find a phenomenon that reproduces

![image](https://user-images.githubusercontent.com/10924072/113502945-0a7d7c00-956a-11eb-9f4b-e78ef10e5d82.png)

**Comment by hackerwins** [comment]
@ppeeou I think of it as a different problem. The previous problem was with `RGATreeSplit` and this time with `RGATreeList`. First, we need to find a path of reproduction.
