### ISSUE TITLE
Make Drawing Board support Retina display

### ISSUE THREAD

**Issue by hackerwins** [yorkie-team/yorkie-codepair#50]
**Description**:

Make Drawing Board support Retina display.

**Why**:

Users can see sharper lines on the drawing board.

**Comment by ppeeou** [comment]
@hackerwins  Can I capture what it looks like on a Retina display??

**Comment by hackerwins** [comment]
@ppeeou The borders of the lines look a little blurry on the Retina display.

<img width="732" alt="Screen Shot 2021-03-07 at 8 42 49 PM" src="https://user-images.githubusercontent.com/2059311/110238577-b3de4b80-7f85-11eb-970f-50b96bcaee71.png">

I have no experience solving it, but I have been able to find some solutions.

https://stackoverflow.com/questions/35820750/understanding-html-retina-canvas-support
https://coderwall.com/p/vmkk6a/how-to-make-the-canvas-not-look-like-crap-on-retina
