### ISSUE TITLE
Add eraser to Drawing Board

### ISSUE THREAD

**Issue by hackerwins** [yorkie-team/yorkie-codepair#51]
**Description**:

Add eraser to Drawing Board.
The UI that deletes the line that touches the eraser like Zoom's Annotation tool looks good.

**Why**:

It is difficult to draw something because users cannot delete lines.

**Comment by ppeeou** [comment]
@hackerwins  Could I try this issue??

**Comment by hackerwins** [comment]
@ppeeou Sure.
